# Generated by Django 2.1.5 on 2019-01-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='voltage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
