# Generated by Django 2.1.5 on 2019-01-19 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20190119_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='content',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='title',
        ),
    ]
